# Site settings
title: Mental Blabberings
email: dean@mentalblabberings.com
description: > # this means to ignore newlines until "baseurl:"
  Insights from Chilling Out.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mentalblabberings.com" # the base hostname & protocol for your site
twitter_username: deanberris
github_username:  deanberris

# Build settings
markdown: kramdown
